package beamerkun.scalemanager.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import java.util.Date;

import static java.lang.System.*;
// KEEP INCLUDES END
/**
 * Entity mapped to table "MEASUREMENT".
 */
public class Measurement {

    private Long id;
    private java.util.Date date;
    private Float weight;
    private Float bodyFat;
    private Float bodyWater;
    private Float boneWeight;
    private Float muscleMass;
    private Integer visceralFat;
    private Integer BMR;
    private Float BMI;
    private long userId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Measurement() {
    }

    public Measurement(Long id) {
        this.id = id;
    }

    public Measurement(Long id, java.util.Date date, Float weight, Float bodyFat, Float bodyWater, Float boneWeight, Float muscleMass, Integer visceralFat, Integer BMR, Float BMI, long userId) {
        this.id = id;
        this.date = date;
        this.weight = weight;
        this.bodyFat = bodyFat;
        this.bodyWater = bodyWater;
        this.boneWeight = boneWeight;
        this.muscleMass = muscleMass;
        this.visceralFat = visceralFat;
        this.BMR = BMR;
        this.BMI = BMI;
        this.userId = userId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public Float getWeight() {
        return weight;
    }

    public void setWeight(Float weight) {
        this.weight = weight;
    }

    public Float getBodyFat() {
        return bodyFat;
    }

    public void setBodyFat(Float bodyFat) {
        this.bodyFat = bodyFat;
    }

    public Float getBodyWater() {
        return bodyWater;
    }

    public void setBodyWater(Float bodyWater) {
        this.bodyWater = bodyWater;
    }

    public Float getBoneWeight() {
        return boneWeight;
    }

    public void setBoneWeight(Float boneWeight) {
        this.boneWeight = boneWeight;
    }

    public Float getMuscleMass() {
        return muscleMass;
    }

    public void setMuscleMass(Float muscleMass) {
        this.muscleMass = muscleMass;
    }

    public Integer getVisceralFat() {
        return visceralFat;
    }

    public void setVisceralFat(Integer visceralFat) {
        this.visceralFat = visceralFat;
    }

    public Integer getBMR() {
        return BMR;
    }

    public void setBMR(Integer BMR) {
        this.BMR = BMR;
    }

    public Float getBMI() {
        return BMI;
    }

    public void setBMI(Float BMI) {
        this.BMI = BMI;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    // KEEP METHODS - put your custom methods here
    public Measurement(byte[] bytes) {
        date = new Date();
        weight = ((bytes[4] << 8) + bytes[5]) / 10f;
        bodyFat = ((bytes[6] << 8) + bytes[7]) / 10f;
        bodyWater = ((bytes[8] << 8) + bytes[9]) / 10f;
        boneWeight = ((bytes[10] << 8) + bytes[11]) / 10f;
        muscleMass = ((bytes[12] << 8) + bytes[13]) / 10f;
        visceralFat = (int)bytes[14];
        BMR = (bytes[15] << 8) + bytes[16];
        BMI = ((bytes[17] << 8) + bytes[18]) / 10f;
    }
    // KEEP METHODS END

}
